image: Visual Studio 2017

branches:
  only:
    - master

cache:
  - Gforum\packages -> **\packages.config

before_build:
  - nuget restore GForum\GForum.sln

configuration: Release

build:
  project: GForum\GForum.sln
  verbosity: minimal
  publish_wap: true

test_script:
  - ps: >-
      GForum\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe
      -register:user
      -target:"GForum\packages\NUnit.ConsoleRunner.3.7.0\tools\nunit3-console.exe"
      -targetargs:"$(ls -r Gforum\*\bin\$configuration\*.Tests.dll | % FullName)"
      -filter:"+[*]* -[*.Tests]*"
      -output:".\coverage.xml"
  - ps: GForum\packages\Codecov.1.0.3\tools\codecov.exe -f ".\coverage.xml"

deploy:
  provider: WebDeploy
  server: https://gforum-mvc.scm.azurewebsites.net:443/msdeploy.axd?site=gforum-mvc
  website: gforum-mvc
  username: $gforum-mvc
  password: 
    secure: M69u+JBNrtCkgyZpo6/OFYdU9i95TinkyWObdqXZafDKra2AYfNd4ucvOXpgOlxHMOxcOulhDIKRKm1EFbAAEw==